/// GUI
#macro GUI_WIDTH 960 
#macro GUI_HEIGHT 540 

/// ENEMY PARENT
#macro ENEMY_SMART_SEARCH 11


/// CAMERA
#macro CAMERA_RESET_PAN 0
#macro CAMERA_SCREEN_SHAKE 1
#macro CAMERA_DISABLE_SHADER 2

/// Player
#macro KNOCKED_BACK 0
#macro JET_PACK_JUMP 1
#macro PREVIOUS_HP 2
#macro PLAYER_DISABLE_SHADER 3

/// FROG
#macro FROG_RESET_JUMP 1

/// Slime
#macro SLIME_ROAM 1

