/// GUI
#macro GUI_WIDTH 960 
#macro GUI_HEIGHT 540 

/// ENEMY PARENT
#macro ENEMY_SMART_SEARCH 11
#macro ENEMY_ROAM 1
#macro ENEMY_IMAGE_ALPHA 2
#macro ENEMY_ATTACK_DELAY 4


/// CAMERA
#macro CAMERA_RESET_PAN 0
#macro CAMERA_SCREEN_SHAKE 1
#macro CAMERA_DISABLE_SHADER 2

/// Player
#macro KNOCKED_BACK 0
#macro JET_PACK_JUMP 1
#macro PREVIOUS_HP 2
#macro PLAYER_IMAGE_ALPHA 3
#macro PLAYER_ATTACK_DELAY 4

/// FROG
#macro FROG_RESET_JUMP 1

/// Slime
#macro SLIME_ROAM 1

